# Generated by Django 6.0.4 on 2026-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('host_name', models.CharField()),
                ('process_name', models.CharField()),
                ('process_id', models.PositiveIntegerField()),
                ('raw_message', models.CharField(max_length=255)),
                ('source', models.CharField()),
                ('source_ip', models.CharField()),
                ('source_port', models.PositiveIntegerField()),
                ('destination_ip', models.CharField()),
                ('event_type', models.CharField()),
                ('ssh_key_fingerprint', models.CharField()),
                ('username', models.CharField()),
                ('tty', models.CharField()),
                ('working_directory', models.CharField()),
                ('target_user', models.CharField()),
                ('command', models.CharField()),
                ('session_action', models.CharField()),
                ('pam_service', models.CharField()),
                ('session_id', models.CharField()),
            ],
        ),
    ]
