# Generated by Django 6.0.4 on 2026-04-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZeekConnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('source_port', models.PositiveIntegerField()),
                ('dest_ip', models.GenericIPAddressField(db_index=True)),
                ('dest_port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('duration', models.FloatField(null=True)),
                ('bytes_orig', models.BigIntegerField(null=True)),
                ('bytes_resp', models.BigIntegerField(null=True)),
                ('conn_state', models.CharField(max_length=10)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
