# Generated by Django 6.0.4 on 2026-04-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_entries', '0002_zeekconnlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zeekconnlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='history',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='ip_proto',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='local_orig',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='local_resp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='missed_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='orig_ip_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='orig_pkts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='resp_ip_bytes',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='resp_pkts',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='tunnel_parents',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zeekconnlog',
            name='uid',
            field=models.CharField(db_index=True, default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zeekconnlog',
            name='bytes_orig',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zeekconnlog',
            name='bytes_resp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zeekconnlog',
            name='conn_state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zeekconnlog',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='zeekconnlog',
            index=models.Index(fields=['timestamp', 'conn_state'], name='log_entries_timesta_9c6396_idx'),
        ),
        migrations.AddIndex(
            model_name='zeekconnlog',
            index=models.Index(fields=['source_ip', 'dest_ip'], name='log_entries_source__6443ac_idx'),
        ),
    ]
